### ISSUE TITLE
Role fails to pull aiidalab Docker image

### ISSUE THREAD

**Issue by JPchico** [aiidalab/ansible-playbook-aiidalab-server#8]
I was trying to deploy the server in an ubuntu 22.04 VM in azure and I got the following error
```
TASK [marvel-nccr.aiidalab_server : pull docker image] ************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: argument of type 'bool' is not iterable
fatal: [aiidalab]: FAILED! => changed=false 
  module_stderr: |-
    Traceback (most recent call last):
      File "<stdin>", line 107, in <module>
      File "<stdin>", line 99, in _ansiballz_main
      File "<stdin>", line 47, in invoke_module
      File "/usr/lib/python3.8/runpy.py", line 207, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_docker_image_payload_lwly95gd/ansible_docker_image_payload.zip/ansible_collections/community/docker/plugins/modules/docker_image.py", line 925, in <module>
      File "/tmp/ansible_docker_image_payload_lwly95gd/ansible_docker_image_payload.zip/ansible_collections/community/docker/plugins/modules/docker_image.py", line 891, in main
      File "/tmp/ansible_docker_image_payload_lwly95gd/ansible_docker_image_payload.zip/ansible_collections/community/docker/plugins/module_utils/common.py", line 595, in __init__
      File "/tmp/ansible_docker_image_payload_lwly95gd/ansible_docker_image_payload.zip/ansible/module_utils/basic.py", line 502, in __init__
      File "/tmp/ansible_docker_image_payload_lwly95gd/ansible_docker_image_payload.zip/ansible/module_utils/common/arg_spec.py", line 268, in validate
      File "/tmp/ansible_docker_image_payload_lwly95gd/ansible_docker_image_payload.zip/ansible/module_utils/common/arg_spec.py", line 236, in validate
      File "/tmp/ansible_docker_image_payload_lwly95gd/ansible_docker_image_payload.zip/ansible/module_utils/common/parameters.py", line 730, in _validate_sub_spec
      File "/tmp/ansible_docker_image_payload_lwly95gd/ansible_docker_image_payload.zip/ansible/module_utils/common/parameters.py", line 806, in set_fallbacks
    TypeError: argument of type 'bool' is not iterable
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

PLAY RECAP ********************************************************************************************************************************************************************************************************
aiidalab                   : ok=29   changed=15   unreachable=0    failed=1    skipped=10   rescued=0    ignored=0   

```

It seems that something goes wrong when it is pulling the docker image for aiidalab?  If I check with the `-vvv` it seems that  it has problems with the ssh connection? Which seems quite strange since it seems to be able to do the rest of the operations. Which leads me to believe that the problem is something else.

I tried deploying another VM with ubuntu 18.4 to test if the issue is related with the OS version and then I found the following error:
```
TASK [marvel-nccr.aiidalab_server : pull docker image] ************************************************************************************************************************************************************
fatal: [aiidalab]: FAILED! => changed=false 
  module_stderr: |-
    /usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.26.10) or chardet (3.0.4) doesn't match a supported version!
      RequestsDependencyWarning)
    Traceback (most recent call last):
      File "<stdin>", line 107, in <module>
      File "<stdin>", line 99, in _ansiballz_main
      File "<stdin>", line 48, in invoke_module
      File "/usr/lib/python3.6/runpy.py", line 205, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
        mod_name, mod_spec, pkg_name, script_name)
      File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_docker_image_payload_320i9i0q/ansible_docker_image_payload.zip/ansible_collections/community/docker/plugins/modules/docker_image.py", line 925, in <module>
      File "/tmp/ansible_docker_image_payload_320i9i0q/ansible_docker_image_payload.zip/ansible_collections/community/docker/plugins/modules/docker_image.py", line 897, in main
      File "/tmp/ansible_docker_image_payload_320i9i0q/ansible_docker_image_payload.zip/ansible_collections/community/docker/plugins/module_utils/common.py", line 601, in __init__
      File "/tmp/ansible_docker_image_payload_320i9i0q/ansible_docker_image_payload.zip/ansible/module_utils/basic.py", line 502, in __init__
      File "/tmp/ansible_docker_image_payload_320i9i0q/ansible_docker_image_payload.zip/ansible/module_utils/common/arg_spec.py", line 268, in validate
      File "/tmp/ansible_docker_image_payload_320i9i0q/ansible_docker_image_payload.zip/ansible/module_utils/common/arg_spec.py", line 239, in validate
      File "/tmp/ansible_docker_image_payload_320i9i0q/ansible_docker_image_payload.zip/ansible/module_utils/common/parameters.py", line 730, in _validate_sub_spec
      File "/tmp/ansible_docker_image_payload_320i9i0q/ansible_docker_image_payload.zip/ansible/module_utils/common/parameters.py", line 806, in set_fallbacks
    TypeError: argument of type 'bool' is not iterable
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

PLAY RECAP ********************************************************************************************************************************************************************************************************
aiidalab                   : ok=32   changed=22   unreachable=0    failed=1    skipped=8    rescued=0    ignored=0 
```

The error now seems to be the version of certain python libraries, for what I can see. 

Any suggestions on what could solve this issue? 

I think having support for 20.04 would be very good since 18.04 since next year it is scheduled to be in the end of standard support.

**Comment by ltalirz** [comment]
@csadorf @yakutovicha

**Comment by yakutovicha** [comment]
@JPchico, thanks for the report. I just tried to rerun the role, and it seemed to work on my machine. Can you share your ansible version, so we can try to investigate the issue?

For your information, the aiidalab host I tried to run is Ubuntu 20.04.

Here is the output of `ansible --version`:
```
ansible [core 2.11.5]
  config file = /Users/yakutovicha/Documents/openstack-ansible/ansible.cfg
  configured module search path = ['/Users/yakutovicha/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/yakutovicha/anaconda3/lib/python3.7/site-packages/ansible
  ansible collection location = /Users/yakutovicha/Documents/openstack-ansible/collections
  executable location = /Users/yakutovicha/anaconda3/bin/ansible
  python version = 3.7.3 (default, Mar 27 2019, 16:54:48) [Clang 4.0.1 (tags/RELEASE_401/final)]
  jinja version = 2.10.1
  libyaml = True
```

**Comment by ltalirz** [comment]
note that Jonathan may be using https://github.com/aiidalab/ansible-playbook-aiidalab-server
please check whether the way this playbook uses the role still works

**Comment by JPchico** [comment]
Sorry yes! I just now realize that the repo name is different got a bit
confused. But Leopold is right I'm using the playbook.

I'm currently ill so I can't check it now but I'll try to do it tomorrow.

**Comment by yakutovicha** [comment]
> note that Jonathan may be using https://github.com/aiidalab/ansible-playbook-aiidalab-server please check whether the way this playbook uses the role still works

oh, thanks @ltalirz for clarifying. I will have a look at https://github.com/aiidalab/ansible-playbook-aiidalab-server. I think it was not updated for a while and needs a revision.

**Comment by JPchico** [comment]
Hi @yakutovicha I have managed to checked the ansible version as you suggested
```
ansible [core 2.13.2]
  config file = None
  configured module search path = ['/home/jonathan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jonathan/anaconda3/envs/aiidalab_server/lib/python3.9/site-packages/ansible
  ansible collection location = /home/jonathan/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/jonathan/anaconda3/envs/aiidalab_server/bin/ansible
  python version = 3.9.12 (main, Jun  1 2022, 11:38:51) [GCC 7.5.0]
  jinja version = 3.1.2
  libyaml = True
```

I also wonder if I should move this issue to the playbook git instead. Sorry for the confusion, I was a bit ill when I was deploying this and the similar name tripped me up.

**Comment by yakutovicha** [comment]
> I also wonder if I should move this issue to the playbook git instead

I think yes, that would be a better place for the issue. I will move the issue, don't worry.

**Comment by JPchico** [comment]
I was looking at this and I'm not sure if this is the cause of the issue and I "managed" to make it work by changing the version of the `aiidalab_server` role by setting the version number to `0.3.0` from `0.2.1`
```
---
- src: marvel-nccr.aiidalab_server
  version: v0.3.0
# - src: geerlingguy.certbot
#   version: 3.0.2
```
in the `requirements.yml`

However, after it was deployed I tried to connect to the server and I got the following error

```
Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
Apache/2.4.41 (Ubuntu) Server at 20.101.151.199 Port 80
```

I wonder if this is something expected or if there is something else from the documentation that I have to add.

Something I did needed to do as I was running with Ubuntu `20.04`  I had to remove by hand the following lines 
```
      - python-pip
      - python-setuptools
      - python-wheel
```
from the  `roles/marvel-ncrr.aiidalab_server/tasks/prerequisites.yml` file. These have been removed from the master but they are present in the `0.3.0` release. 

I can make a PR updating the playbook, however I think it might be best to first have a new release from the role. What do you think @yakutovicha ?

**Comment by yakutovicha** [comment]
> I think it might be best to first have a new release from the role. What do you think @yakutovicha?

Thanks, @JPchico, it is done. I just tagged version 0.4.0, but the issue is a bit deeper, unfortunately.

We wanted to collect aiidalab roles in separate aiidalab namespace: https://github.com/ansible/galaxy/issues/2480.

All went fine until I tried to add roles to the namespace, then this occurred: https://github.com/ansible/galaxy/issues/2820. Unfortunately, the developers have ignored me for 9 months already. If you know any way to draw their attention to the issue, by all means, use it :)

The only thing you can do for now is just pulling the latest changes from the master branch ¯\\\_\(ツ\)\_/¯

> I can make a PR updating the playbook, 

Thanks, that would be great.

For your information, I am going to be on vacation until the 16ths of August. Working on role/playbook will be the first thing for me after the return.

**Comment by JPchico** [comment]
> Thanks, @JPchico, it is done. I just tagged version 0.4.0, but the issue is a bit deeper, unfortunately.

Hi @yakutovicha thanks for the help! 

> We wanted to collect aiidalab roles in separate aiidalab namespace: https://github.com/ansible/galaxy/issues/2480.
>
>All went fine until I tried to add roles to the namespace, then this occurred: https://github.com/ansible/galaxy/issues/2820. Unfortunately, the developers have ignored me for 9 months already. If you know any way to draw their attention to the issue, by all means, use it :)

I see, I can try adding my voice to the issue, I'm unsure if that would help much, but hey it at least cannot hurt.

Just one last question, when I managed to deploy (with the 0.3.0 tag)  it I go the following error, is this related to the issue with the namespaces? Or is it something with my azure configuration? I had both the http (80) and the https (443) ports open, but perhaps I'm missing something

> Service Unavailable
>
>The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
>Apache/2.4.41 (Ubuntu) Server at 20.101.151.199 Port 80


> For your information, I am going to be on vacation until the 16ths of August. Working on role/playbook will be the first thing for me after the return.

Enjoy your holidays! And thanks for your help.

**Comment by yakutovicha** [comment]
> Just one last question, when I managed to deploy (with the 0.3.0 tag) it I go the following error, is this related to the issue with the namespaces? Or is it something with my azure configuration? I had both the http (80) and the https (443) ports open, but perhaps I'm missing something

It looks to me that JupyterHub failed to start. I would really suggest pulling the latest changes on the role's master branch and rerun everything. It might just magically fix it. Version 0.3.0 is quite outdated, I would say (18 Jun 2020).

> Enjoy your holidays! And thanks for your help.

Thanks!

**Comment by JPchico** [comment]
I tried updating the playbook to the `0.4.0` but it does not seems to find it? I'm unsure if it something that is temporary or something else. Maybe the build has not been uploaded to the server it needs? When I looked in the [ansible-galaxy webpage](https://galaxy.ansible.com/marvel-nccr/aiidalab_server) I only see until version `0.3.0` so my guess is that the role is still not uploaded there. 

The error I get is the following
```
[WARNING]: - marvel-nccr.aiidalab_server was NOT installed successfully: - the specified version (v0.4.0) of marvel-nccr.aiidalab_server was not found in the list of available versions ([{'id': 99132, 'url':
'', 'related': {}, 'summary_fields': {}, 'created': '2019-07-17T16:07:52.066399Z', 'modified': '2019-07-17T16:07:52.066427Z', 'name': 'v0.1.0', 'version': '0.1.0', 'commit_date': '2019-07-17T12:03:12-04:00',
'commit_sha': '01b3e97bc90f38831fa427f13642b2990f90d5dd', 'download_url': 'https://github.com/marvel-nccr/ansible-role-aiidalab-server/archive/v0.1.0.tar.gz', 'active': None}, {'id': 104651, 'url': '',
'related': {}, 'summary_fields': {}, 'created': '2019-09-27T12:45:46.403415Z', 'modified': '2019-09-27T12:45:46.403454Z', 'name': 'v0.1.1', 'version': '0.1.1', 'commit_date': '2019-09-27T08:33:36-04:00',
'commit_sha': '93472ed4a0c77f07d7cfcd732a462c2b9e928739', 'download_url': 'https://github.com/marvel-nccr/ansible-role-aiidalab-server/archive/v0.1.1.tar.gz', 'active': None}, {'id': 104708, 'url': '',
'related': {}, 'summary_fields': {}, 'created': '2019-09-29T20:12:27.236200Z', 'modified': '2019-09-29T20:12:27.236229Z', 'name': 'v0.1.2', 'version': '0.1.2', 'commit_date': '2019-09-29T16:00:26-04:00',
'commit_sha': 'ea3ad206ae534693131ae5f84dbc99f4abc32675', 'download_url': 'https://github.com/marvel-nccr/ansible-role-aiidalab-server/archive/v0.1.2.tar.gz', 'active': None}, {'id': 104746, 'url': '',
'related': {}, 'summary_fields': {}, 'created': '2019-09-30T21:12:24.865880Z', 'modified': '2019-09-30T21:12:24.865922Z', 'name': 'v0.1.3', 'version': '0.1.3', 'commit_date': '2019-09-30T17:00:23-04:00',
'commit_sha': '63630d97fee8cc311edd1513c3bff0728dbb5349', 'download_url': 'https://github.com/marvel-nccr/ansible-role-aiidalab-server/archive/v0.1.3.tar.gz', 'active': None}, {'id': 108378, 'url': '',
'related': {}, 'summary_fields': {}, 'created': '2019-11-07T18:23:12.673969Z', 'modified': '2019-11-07T18:23:12.673997Z', 'name': 'v0.2.0', 'version': '0.2.0', 'commit_date': '2019-11-07T13:10:51-05:00',
'commit_sha': '4bd5912034467a21e294cf1695a59bf591399024', 'download_url': 'https://github.com/marvel-nccr/ansible-role-aiidalab-server/archive/v0.2.0.tar.gz', 'active': None}, {'id': 114733, 'url': '',
'related': {}, 'summary_fields': {}, 'created': '2020-01-29T00:36:42.004733Z', 'modified': '2020-01-29T00:36:42.004759Z', 'name': 'v0.2.1', 'version': '0.2.1', 'commit_date': '2020-01-28T19:14:04-05:00',
'commit_sha': '25137f435c280d2e503d180bf1d786dc731fe212', 'download_url': 'https://github.com/marvel-nccr/ansible-role-aiidalab-server/archive/v0.2.1.tar.gz', 'active': None}, {'id': 134466, 'url': '',
'related': {}, 'summary_fields': {}, 'created': '2020-08-24T08:46:52.485363Z', 'modified': '2020-08-24T08:46:52.485392Z', 'name': 'v0.3.0', 'version': '0.3.0', 'commit_date': '2020-06-18T14:31:16-04:00',
'commit_sha': '9057f349f2a4fe5372628390d79a179079af60e5', 'download_url': 'https://github.com/marvel-nccr/ansible-role-aiidalab-server/archive/v0.3.0.tar.gz', 'active': None}]).
```

**Comment by yakutovicha** [comment]
> I tried updating the playbook to the `0.4.0` but it does not seems to find it? I'm unsure if it something that is temporary or something else. Maybe the build has not been uploaded to the server it needs? When I looked in the [ansible-galaxy webpage](https://galaxy.ansible.com/marvel-nccr/aiidalab_server) I only see until version `0.3.0` so my guess is that the role is still not uploaded there.

Just pull it from the github, it is what I meant earlier:

> I would really suggest pulling the latest changes on the role's master branch

Place it in the same location as the previous version.

**Comment by JPchico** [comment]
aha, okay I misunderstood, great will do that then.

**Comment by JPchico** [comment]
Okay after pulling the latest version to the roles I'm getting an error with the jupyter-hub service

```
TASK [marvel-nccr.aiidalab_server : (re)start JupyterHub service] *************************************************************************************************************************************************
fatal: [aiidalab]: FAILED! => changed=false 
  msg: 'Could not find the requested service jupyterhub: host'

PLAY RECAP ********************************************************************************************************************************************************************************************************
aiidalab                   : ok=28   changed=1    unreachable=0    failed=1    skipped=13   rescued=0    ignored=0   
```

This is with pulling the `0.4.0` from the github and then just running `ansible-playbook playbook.yml --ask-become-pass`

My `roles` folder looks like this `geerlingguy.docker  marvel-nccr.aiidalab_server` with `geerlingguy.docker` being the one installed via `ansible-galaxy install -r requirements.yml` and `marvel-nccr.aiidalab_server` being `git clone https://github.com/aiidalab/ansible-role-aiidalab-server.git marvel-nccr.aiidalab_server`

**Comment by yakutovicha** [comment]
Maybe recreate the machine? It looks like Jupyterhub was not correctly installed by the previous runs.

**Comment by JPchico** [comment]
Yeah, it was a clean machine but I can try it again with another fresh VM

**Comment by JPchico** [comment]
I ran into the same problem with a fresh VM, I tried with a more verbose run to see if I could see the problem and this is what I got

```
Escalation succeeded
debug1: Reading configuration data /home/jonathan/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug2: resolve_canonicalize: hostname VM_IP_ADDRESS is address
debug1: auto-mux: Trying existing master
debug2: fd 3 setting O_NONBLOCK
debug2: mux_client_hello_exchange: master version 4
debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
debug3: mux_client_request_session: entering
debug3: mux_client_request_alive: entering
debug3: mux_client_request_alive: done pid = 47738
debug3: mux_client_request_session: session request sent
debug3: mux_client_read_packet: read header failed: Broken pipe
debug2: Received exit status from master 1
fatal: [aiidalab]: FAILED! => changed=false 
  invocation:
    module_args:
      daemon_reexec: false
      daemon_reload: true
      enabled: true
      force: null
      masked: null
      name: jupyterhub
      no_block: false
      scope: system
      state: restarted
  msg: 'Could not find the requested service jupyterhub: host'
````

So my guess is that I need to change something in the `jupyterhub_config`

**Comment by ltalirz** [comment]
hey @yakutovicha 
looks like you accidentally removed the juptyerhub system service in https://github.com/aiidalab/ansible-role-aiidalab-server/commit/93e2c10151b3be67c4511e559fe13ad63fc60d92

This is not caught on CI because there is no systemd inside the docker image (or at least the restart step that errored here is disabled there)

Please fix!

**Comment by JPchico** [comment]
@ltalirz I have confirmed that those deleted lines were the problem I added them by hand and the server works! I can make a little PR for that in the ansible role git fixing this.

**Comment by JPchico** [comment]
@ltalirz and @yakutovicha I made a little PR to solve the proble with the missing jupyterhub service https://github.com/aiidalab/ansible-role-aiidalab-server/pull/37

**Comment by yakutovicha** [comment]
Hey @JPchico, what is the status here? I came back from the holidays, so I can now focus on the issue.

My plan is to bring the repository to the working state so that I can successfully deploy a machine using it.

**Comment by JPchico** [comment]
Hey @yakutovicha, we fixed some issues in the ansible-role and that makes that if one clones that role into the task then it is possible to deploy the server using the playbook. I think what is missing is to have a new release of the role that includes that [fix](https://github.com/aiidalab/ansible-role-aiidalab-server/pull/37). After that I can make the PR setting the version number in the playbook requirements and then in principle it should be possible to deploy using this.

**Comment by yakutovicha** [comment]
> I think what is missing is to have a new release of the role that includes that [fix](https://github.com/aiidalab/ansible-role-aiidalab-server/pull/37).

I think making a new release will bring nothing, till https://github.com/ansible/galaxy/issues/2820 is fixed :(.

The new release won't be available on the ansible galaxy.

**Comment by csadorf** [comment]
Just thinking out loud to unblock this: is it 100% necessary to release as part of the aiidalab namespace? Or could we potentially release it in a different namespace?

**Comment by yakutovicha** [comment]
> Just thinking out loud to unblock this: is it 100% necessary to release as part of the aiidalab namespace? Or could we potentially release it in a different namespace?

Alright, that is also an option. But this would require transferring the ansible role repository to the `marvel-nccr` organisation. Alternatively, we could put a link to the github repository here: https://github.com/aiidalab/ansible-playbook-aiidalab-server/blob/8b962ef06e780b5b6aa87c461bf40c7fcceeaf20/requirements.yml#L2 as in one of [the examples](https://stackoverflow.com/questions/55773505/where-to-place-requirements-yml-for-ansible-and-use-it-to-resolve-dependencies). What do you guys think?

**Comment by yakutovicha** [comment]
Hey @JPchico, I think after a few changes the playbook should be operational. Can you please test it? Thanks!

**Comment by JPchico** [comment]
Hi @yakutovicha , it does indeed work! Thanks! Now I have to take sometime to work in the configuration to add security and things like this. Something that I would also like to do is to decouple some of the services (namely the database) from the instance and instead have a remote psql server. I'll keep you guys informed on how my experiments go.
